FROM centos7-base-image:latest

WORKDIR /usr/src/app

COPY --chmod=755 requirements.txt ./
COPY --chmod=755 src/demo-logo.png ./
COPY --chmod=755 src/demo-partner-pic.png ./
COPY --chmod=755 src/simFinTrans.py ./
COPY --chmod=755 src/simFinTransReceiver.py ./
COPY --chmod=755 src/simMain.py ./
COPY --chmod=755 scripts/sim.env ./ 
COPY --chmod=755 scripts/sim.sh ./ 
COPY --chmod=755 scripts/simKafkaProducer.sh ./ 
COPY --chmod=755 data/maryland-pg-county.csv ./
COPY --chmod=755 data/sf-bay-area.csv ./

RUN pip3 install --no-cache-dir -r requirements.txt \
    && curl "https://downloads.apache.org/kafka/3.7.0/kafka_2.13-3.7.0.tgz" -o kafka.tgz \
    && mkdir kafka && cd kafka \    
    && tar -xvzf ../kafka.tgz --strip 1   
