version: "1.0"
services:
  udp-producer:
    image: kafka-client:latest
    environment:
      SIM_HOME: /usr/src/app
      SIM_TIMEZONE: US/Eastern
      SIM_DATA_FILE: /usr/src/app/sf-bay-area.csv
      SIM_TARGET_RECEIVER: UDP
      SIM_TARGET_UDP_HOST: localhost
      SIM_TARGET_UDP_PORT: 6901
    command: sh -c "./sim.sh start && ./sim.sh test"
    ports:
      - "6901:6901"
    networks:
      - csp-ce-net
    stdin_open: true 
    tty: true
  notebook:
    image: jupyter-r:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PASSWORD=password
    volumes:
      - ./mounts/notebook:/home/jovyan/work
    command: jupyter notebook --no-browser --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "8888:8888"
    networks:
      - csp-ce-net
    stdin_open: true 
    tty: true

networks:
  csp-ce-net:
    driver: bridge

