FROM jupyter/r-notebook
USER root
RUN  apt-get update -y \ 
        && apt-get install -y libproj-dev libgdal-dev \
        && conda install --yes \
        r-httr2 r-jsonlite r-dplyr r-tidyjson r-data.table r-ggplot2 \
        r-showtext r-ggtext r-tidyr \   
        && conda clean --all --yes \ 
        && R -e "remotes::install_version('scales', repos='http://cran.rstudio.com/', version = '>= 1.3.0')" \
        && R -e "install.packages('proj4', repos='http://cran.rstudio.com/', dependencies = T)" \
        && R -e "install.packages('osmdata', repos='http://cran.rstudio.com/', dependencies = T)" \
        && R -e "install.packages('plotly', repos='http://cran.rstudio.com/', dependencies = T)"
ENV JUPYTER_ENABLE_LAB=yes
USER jovyan
